repos:
  # This should be before any formatting hooks like isort
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.1.15"
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-ast
      - id: debug-statements
      - id: check-added-large-files
        args: ['--maxkb=750']
      - id: check-case-conflict
      - id: trailing-whitespace
        exclude: ".*(.fits|.asdf)"
      - id: mixed-line-ending
        files: ".*.py"
      - id: end-of-file-fixer
        exclude: ".*(.fits|.asdf|.json)"
ci:
  autofix_prs: false
